### Get all
GET http://localhost:3000/api/horariosAtencion

### Get one
GET http://localhost:3000/api/horariosAtencion/1

### Post
# @name createhorariosAtencion
POST http://localhost:3000/api/horariosAtencion
Content-Type: application/json

{
  "sucursal_id": 2,
  "hora_apertura": "14:00:00",
  "hora_cierre": "22:00:00",
  "dia_semana": "Sabados"
}

### Update
PUT http://localhost:3000/api/horariosAtencion/1
Content-Type: application/json

{
  "hora_cierre": "10:30:00"
}

### Delete
DELETE http://localhost:3000/api/horariosAtencion/2