### Get all
GET http://localhost:3000/api/horariosAtencion

### Get one
GET http://localhost:3000/api/horariosAtencion/1

### Post
# @name createhorariosAtencion
POST http://localhost:3000/api/horariosAtencion
Content-Type: application/json

{
  "sucursal_id": 1,
  "hora_apertura": 4.30,
  "hora_cierre": 10.0,
  "dia_seamana": "Domingo"
}

### Update
PUT http://localhost:3000/api/horariosAtencion/1
Content-Type: application/json

{
  "horaCierre": 10.30
}

### Delete
DELETE http://localhost:3000/api/horariosAtencion/2