### Get all
GET http://localhost:3000/api/disenio

### Get all by tattoer
GET http://localhost:3000/api/disenio/tatuador/39453700

### Get all by tattoer
GET http://localhost:3000/api/disenio/cliente/39453700/1

### Get all available
GET http://localhost:3000/api/disenio/cliente/tat

### Get one
GET http://localhost:3000/api/disenio/1

### Post
# @name createdisenio
POST http://localhost:3000/api/disenio
Content-Type: application/json

{
"codigo": 1,
"categoria_codigo": 1,
"tatuador_dni": 39453700,
"tamaño_aproximado": 10,
"imagen": "https://static.vecteezy.com/system/resources/thumbnails/001/227/500/small_2x/traditional-rose-and-dagger-tattoo-design.jpg",
"precio_base": 15000.50,
"descuento": 0.25,
"precio_final": 20000, 
"colores": "ÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑÑ",
"estado": "dis"
}

### Update
PUT http://localhost:3000/api/disenio/1
Content-Type: application/json

{
    "colores": "amarillo, negro, azul"
}


### Delete
DELETE http://localhost:3000/api/disenio/2