### Get all
GET http://localhost:3000/api/turno

### Get one
GET http://localhost:3000/api/turno/2024-10-16T09%3A00%3A00.000Z/2024-10-16T11%3A00%3A00.000Z/2024-10-16T00%3A00%3A00.000Z

### Get by tatuador and fecha
GET http://localhost:3000/api/turno/tatuador/39453700/fecha/2024-11-11

### Get by cliente
GET http://localhost:3000/api/turno/cliente/39453700

### Post
# @name createTurno
POST http://localhost:3000/api/turno
Content-Type: application/json

{
"hora_inicio": "16:00:00", 
"hora_fin": "17:00:00",
"fecha_turno": "2024-07-16 00:00:00",
"tatuador_dni": 39453700,
"cliente_dni": 39453700,
"diseño_id": 5,
"indicaciones":"ta bissen",
"estado": "pen"
}

### Update
PUT http://localhost:3000/api/turno/3
Content-Type: application/json

{
    "estado": "pen"
}

### Delete
DELETE  http://localhost:3000/api/turno/4