### Get all
GET http://localhost:3000/api/cliente

### Get one
GET http://localhost:3000/api/cliente/39453700

### Post admin
POST http://localhost:3000/api/cliente/admin
Content-Type: application/json

{
    "dni": 99999999,
    "email": "admin@gmail.com",
    "contraseña": "admin123"
}

### Post
# @name createCliente
POST http://localhost:3000/api/cliente
Content-Type: application/json

{
    "dni": 39453999,
    "nombreCompleto": "Martin Rodriguez",
    "email": "vetesjoaquin@gmail.com",
    "telefono": "03413041923",
    "estado": 3,
    "contraseña":"genius123"
}

### Update
PUT http://localhost:3000/api/cliente/99999999
Content-Type: application/json

{
    "estado": -99
}

### Delete
DELETE  http://localhost:3000/api/cliente/39453711